//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HighDistinctionTask.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class RegisteredUser
    {
        public RegisteredUser()
        {
            this.Donations = new HashSet<Donation>();
        }
    
        //for this validation technique we can search in google asp.net validation mvc or asp.net regular expression validation mvc

        [Required]
        [DisplayName("User ID:")]
        public int user_id { get; set; }
        [Required]
        [DisplayName("First Name:")]
        public string first_name { get; set; }
        [Required]
        [DisplayName("Last Name:")]
        public string last_name { get; set; }
        [Required]
        [DisplayName("Gender:")]
        public string gender { get; set; }
        [Required]
        [DisplayName("Password:")]
        [RegularExpression(@"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[$@$!%*?&])[A-Za-z\d$@$!%*?&]{8,}" ,
            ErrorMessage = "Password must contain: Minimum 8 characters atleast 1 UpperCase Alphabet, 1 LowerCase Alphabet, 1 Number and 1 Special Character. Ex: PaSs@123 OR pAss@123")]
        public string password { get; set; }
        [Required]
        [DisplayName("Address:")]
        public string address { get; set; }
        [Required]
        [DisplayName("Email:")]
        [RegularExpression(@".*@.*\..*", ErrorMessage = "Please Enter a Valid Email Address. Ex: someone@somewhere.com")]
        public string email { get; set; }
        [Required]
        [DisplayName("Postcode:")]
        public int postcode { get; set; }
        [Required]
        [DisplayName("State:")]
        public string state { get; set; }
    
        public virtual ICollection<Donation> Donations { get; set; }
    }
}
